FROM mcr.microsoft.com/dotnet/sdk:7.0

RUN apt-get update \
    && apt-get install -y --no-install-recommends unzip procps \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /vsdbg

RUN groupadd --gid 1000 dotnet \
    && useradd -s /bin/bash --uid 1000 --gid 1000 -m dotnet
RUN mkdir /app && chown dotnet:dotnet /app
USER dotnet

ENV PATH="$PATH:/home/dotnet/.dotnet/tools"
RUN dotnet tool install -g dotnet-ef --version '6.0.0-*'

ARG APP_VERSION

ENV APP_VERSION=${APP_VERSION}

ENV ASPNETCORE_TEST_CONTENTROOT_EXAMPLEAPP_API='/app/bin'

COPY --chown=dotnet out/integration_tests /app/bin
COPY --chown=dotnet config /app/config

WORKDIR /app/code/tests/ExampleApp.IntegrationTests
SHELL ["/bin/bash", "-c"]
ENTRYPOINT /app/config/run_tests.sh
