<Project>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <NoWarn>CA1812</NoWarn>
  </PropertyGroup>

  <PropertyGroup>
    <TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
    <TestingPlatformCommandLineArguments>$(TestingPlatformCommandLineArguments) --ignore-exit-code 8</TestingPlatformCommandLineArguments>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />

    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Testing.Platform" />

    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.analyzers" />
  </ItemGroup>

  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
          Condition="Exists($([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../')))"/>
</Project>
