<Project>
  <PropertyGroup>
    <Authors>LeanCode</Authors>
    <Description>LeanCode Core library</Description>

    <LangVersion>preview</LangVersion>
    <OutputType>library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <DebugType>portable</DebugType>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-ff4q-64jc-gx98" />
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-55p7-v223-x366" />
  </ItemGroup>

  <Import
    Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))"
    Condition="Exists($([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../')))"
  />
</Project>
