namespace LeanCode.DomainModels.Generators.SourceBuilders;

internal static class PrefixedGuidIdSourceBuilder
{
    private const int ValueLength = 32;

    public static string Build(TypedIdData data)
    {
        var prefix = data.CustomPrefix?.ToLowerInvariant() ?? IdSource.GetDefaultPrefix(data.TypeName);

        var randomFactory = !data.SkipRandomGenerator
            ? $"public static {data.TypeName} New() => new(Guid.CreateVersion7());"
            : "";

        // language=C#
        return $$"""
// <auto-generated />
#nullable enable
namespace {{data.Namespace}}
{
    #pragma warning disable CS8019
    using global::System;
    using global::System.ComponentModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Diagnostics;
    using global::System.Linq.Expressions;
    using global::System.Text;
    using global::System.Text.Json.Serialization;
    using global::LeanCode.DomainModels.Ids;
    #pragma warning restore CS8019

    [JsonConverter(typeof(StringTypedIdConverter<{{data.TypeName}}>))]
    [DebuggerDisplay("{Value}")]
    [ExcludeFromCodeCoverage]
    public readonly partial record struct {{data.TypeName}} : IPrefixedTypedId<{{data.TypeName}}>
    {
        private const int ValueLength = {{ValueLength}};
        private const char Separator = '_';
        private const string TypePrefix = "{{prefix}}";

        public static int MaxLength { get; } = {{ValueLength + 1 + prefix.Length}};
        public static {{data.TypeName}} Empty { get; } = new(Guid.Empty);

        private readonly string? value;

        public string Value => value ?? Empty.Value;
        public bool IsEmpty => value is null || value == Empty;
        public Guid Guid => value is null ? Guid.Empty : Guid.ParseExact(value.AsSpan()[{{prefix.Length + 1}}..], "N");

        private {{data.TypeName}}(string v) => value = v;

        public {{data.TypeName}}(Guid v) => value = string.Create(null, stackalloc char[MaxLength], $"{TypePrefix}{Separator}{v:N}");
        {{randomFactory}}

        public static bool IsValid([NotNullWhen(true)] string? v) => v is not null && IsValid(v.AsSpan());
        public static bool IsValid(ReadOnlySpan<char> v) => TryParse(v, null, out _);

        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "IFormatProvider is ignored for Guid parsing.")]
        public static {{data.TypeName}} Parse(string v, IFormatProvider? provider = null)
        {
            ArgumentNullException.ThrowIfNull(v);
            if (TryParse(v.AsSpan(), provider, out var id))
            {
                return id;
            }
            else
            {
                throw new FormatException(
                    $"The ID has invalid format. It should look like {TypePrefix}{Separator}(id value)."
                );
            }
        }

        [return: NotNullIfNotNull("id")]
        public static {{data.TypeName}}? ParseNullable(string? id) => id is string v ? Parse(v) : ({{data.TypeName}}?)null;

        public static bool TryParse([NotNullWhen(true)] string? v, out {{data.TypeName}} id)
            => TryParse(v, null, out id);

        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "IFormatProvider is ignored for Guid parsing.")]
        public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out {{data.TypeName}} result)
        {
            if (s is null)
            {
                result = default;
                return false;
            }
            return TryParse(s.AsSpan(), provider, out result);
        }

        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "IFormatProvider is ignored for Guid parsing.")]
        public static {{data.TypeName}} Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
        {
            if (TryParse(s, provider, out var result))
            {
                return result;
            }
            else
            {
                throw new FormatException(
                    $"The ID has invalid format. It should look like {TypePrefix}{Separator}(id value)."
                );
            }
        }

        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "IFormatProvider is ignored for Guid parsing.")]
        public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {{data.TypeName}} result)
        {
            if (s.Length == MaxLength
                && s.StartsWith(TypePrefix)
                && s[{{prefix.Length}}] == Separator
                && Guid.TryParseExact(s[{{prefix.Length + 1}}..], "N", out var guid))
            {
                result = new {{data.TypeName}}(guid);
                return true;
            }
            else
            {
                result = default;
                return false;
            }
        }

        public (string prefix, Guid data) Destructure() => (TypePrefix, Guid);

        public bool Equals({{data.TypeName}} other) => Value.Equals(other.Value, StringComparison.Ordinal);
        public int CompareTo({{data.TypeName}} other) => string.Compare(Value, other.Value, StringComparison.Ordinal);
        public override int GetHashCode() => Value.GetHashCode(StringComparison.Ordinal);
        public static implicit operator string({{data.TypeName}} id) => id.Value;

        public static bool operator <({{data.TypeName}} a, {{data.TypeName}} b) => a.CompareTo(b) < 0;
        public static bool operator <=({{data.TypeName}} a, {{data.TypeName}} b) => a.CompareTo(b) <= 0;
        public static bool operator >({{data.TypeName}} a, {{data.TypeName}} b) => a.CompareTo(b) > 0;
        public static bool operator >=({{data.TypeName}} a, {{data.TypeName}} b) => a.CompareTo(b) >= 0;

        static Expression<Func<string, {{data.TypeName}}>> IPrefixedTypedId<{{data.TypeName}}>.FromDatabase { get; } = d => Parse(d);
        static Expression<Func<{{data.TypeName}}, {{data.TypeName}}, bool>> IPrefixedTypedId<{{data.TypeName}}>.DatabaseEquals { get; } = (a, b) => a == b;

        public override string ToString() => Value;
        public string ToString(string? format, IFormatProvider? formatProvider) => Value;
        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
        {
            if (destination.Length >= Value.Length)
            {
                Value.CopyTo(destination);
                charsWritten = Value.Length;
                return true;
            }
            else
            {
                charsWritten = 0;
                return false;
            }
        }

        public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
            => Encoding.UTF8.TryGetBytes(Value, utf8Destination, out bytesWritten);
    }
}
""";
    }
}
