namespace LeanCode.DomainModels.Generators.SourceBuilders;

internal static class RawIdSourceBuilder
{
    public static string Build(
        TypedIdData data,
        string backingType,
        string converterPrefix,
        string? randomValueGenerator,
        string defaultValue,
        string toStringParam,
        string tryFormatParams
    )
    {
        var randomFactory =
            !data.SkipRandomGenerator && randomValueGenerator is not null
                ? $"public static {data.TypeName} New() => new({randomValueGenerator});"
                : "";

        // language=C#
        return $$"""
// <auto-generated />
#nullable enable
namespace {{data.Namespace}}
{
    #pragma warning disable CS8019
    using global::System;
    using global::System.ComponentModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Diagnostics;
    using global::System.Globalization;
    using global::System.Linq.Expressions;
    using global::System.Text.Json.Serialization;
    using global::LeanCode.DomainModels.Ids;
    #pragma warning restore CS8019

    [JsonConverter(typeof({{converterPrefix}}TypedIdConverter<{{data.TypeName}}>))]
    [DebuggerDisplay("{Value}")]
    [ExcludeFromCodeCoverage]
    public readonly partial record struct {{data.TypeName}} : IRawTypedId<{{backingType}}, {{data.TypeName}}>
    {
        public static {{data.TypeName}} Empty { get; } = new({{defaultValue}});

        public {{backingType}} Value {get;}
        public bool IsEmpty => Value == Empty;

        public {{data.TypeName}}({{backingType}} v) => Value = v;
        {{randomFactory}}

        public static bool IsValid([NotNullWhen(true)] {{backingType}}? v) => v is not null;

        public static {{data.TypeName}} Parse({{backingType}} v) => new {{data.TypeName}}(v);

        [return: NotNullIfNotNull("id")]
        public static {{data.TypeName}}? ParseNullable({{backingType}}? id)
            => id is {{backingType}} v ? Parse(v) : ({{data.TypeName}}?)null;

        public static bool TryParse([NotNullWhen(true)] {{backingType}}? v, out {{data.TypeName}} id)
        {
            if (IsValid(v))
            {
                id = new {{data.TypeName}}(v.Value);
                return true;
            }
            else
            {
                id = default;
                return false;
            }
        }

        public static {{data.TypeName}} Parse(string s, IFormatProvider? provider = null)
        {
            ArgumentNullException.ThrowIfNull(s);
            if (TryParse(s.AsSpan(), provider, out var result))
            {
                return result;
            }
            else
            {
                throw new FormatException($"Unable to parse '{s}' as {{data.TypeName}}.");
            }
        }

        public static bool TryParse([NotNullWhen(true)] string? v, out {{data.TypeName}} id)
            => TryParse(v, null, out id);

        public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out {{data.TypeName}} result)
        {
            if (s is null)
            {
                result = default;
                return false;
            }
            return TryParse(s.AsSpan(), provider, out result);
        }

        public static {{data.TypeName}} Parse(ReadOnlySpan<char> s, IFormatProvider? provider = null)
        {
            if (TryParse(s, provider, out var result))
            {
                return result;
            }
            else
            {
                throw new FormatException($"Unable to parse the span as {{data.TypeName}}.");
            }
        }

        public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {{data.TypeName}} result)
        {
            if ({{backingType}}.TryParse(s, provider, out var v))
            {
                result = new {{data.TypeName}}(v);
                return true;
            }
            else
            {
                result = default;
                return false;
            }
        }

        public bool Equals({{data.TypeName}} other) => Value == other.Value;
        public int CompareTo({{data.TypeName}} other) => Value.CompareTo(other.Value);
        public override int GetHashCode() => Value.GetHashCode();
        public static implicit operator {{backingType}}({{data.TypeName}} id) => id.Value;

        public static bool operator <({{data.TypeName}} a, {{data.TypeName}} b) => a.Value < b.Value;
        public static bool operator <=({{data.TypeName}} a, {{data.TypeName}} b) => a.Value <= b.Value;
        public static bool operator >({{data.TypeName}} a, {{data.TypeName}} b) => a.Value > b.Value;
        public static bool operator >=({{data.TypeName}} a, {{data.TypeName}} b) => a.Value >= b.Value;

        static Expression<Func<{{backingType}}, {{data.TypeName}}>> IRawTypedId<{{backingType}}, {{data.TypeName}}>.FromDatabase { get; } = d => Parse(d);
        static Expression<Func<{{data.TypeName}}, {{data.TypeName}}, bool>> IRawTypedId<{{backingType}}, {{data.TypeName}}>.DatabaseEquals { get; } = (a, b) => a == b;

        public override string ToString() => Value.ToString({{toStringParam}});
        public string ToString(string? format, IFormatProvider? formatProvider) => ToString();
        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
            => Value.TryFormat(destination, out charsWritten, {{tryFormatParams}});

        public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
            => Value.TryFormat(utf8Destination, out bytesWritten, {{tryFormatParams}});
    }
}
""";
    }
}
