namespace LeanCode.DomainModels.Generators.SourceBuilders;

internal static class RawStringIdSourceBuilder
{
    public static string Build(TypedIdData data)
    {
        var maxValueLength = data.MaxValueLength!.Value;

        // language=C#
        return $$"""
// <auto-generated />
#nullable enable
namespace {{data.Namespace}}
{
    #pragma warning disable CS8019
    using global::System;
    using global::System.ComponentModel;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Diagnostics;
    using global::System.Linq.Expressions;
    using global::System.Text;
    using global::System.Text.Json.Serialization;
    using global::LeanCode.DomainModels.Ids;
    #pragma warning restore CS8019

    [JsonConverter(typeof(RawStringTypedIdConverter<{{data.TypeName}}>))]
    [DebuggerDisplay("{Value}")]
    [ExcludeFromCodeCoverage]
    public readonly partial record struct {{data.TypeName}} : IRawStringTypedId<{{data.TypeName}}>
    {
        public static {{data.TypeName}} Empty { get; } = new(string.Empty);
        public static int MaxLength { get; } = {{maxValueLength}};

        private readonly string? value;

        public string Value => value ?? string.Empty;
        public bool IsEmpty => string.IsNullOrEmpty(value);

        public {{data.TypeName}}(string v) => value = v ?? throw new ArgumentNullException(nameof(v));

        public static bool IsValid([NotNullWhen(true)] string? v) => v is not null && IsValid(v.AsSpan());
        public static bool IsValid(ReadOnlySpan<char> v) => TryParse(v, null, out _);

        public static {{data.TypeName}} Parse(string v) => Parse(v, null);

        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "IFormatProvider is ignored for string length validation.")]
        public static {{data.TypeName}} Parse(string v, IFormatProvider? provider)
        {
            ArgumentNullException.ThrowIfNull(v);
            if (TryParse(v.AsSpan(), provider, out var result))
            {
                return result;
            }
            else
            {
                throw new FormatException(
                    $"The ID has invalid format. It must be a non-null string with maximum length of {MaxLength}.");
            }
        }

        [return: NotNullIfNotNull("id")]
        public static {{data.TypeName}}? ParseNullable(string? id) => id is string v ? Parse(v) : ({{data.TypeName}}?)null;

        public static bool TryParse([NotNullWhen(true)] string? v, out {{data.TypeName}} id)
            => TryParse(v, null, out id);

        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "IFormatProvider is ignored for string length validation.")]
        public static bool TryParse([NotNullWhen(true)] string? s, IFormatProvider? provider, out {{data.TypeName}} result)
        {
            if (s is null)
            {
                result = default;
                return false;
            }
            return TryParse(s.AsSpan(), provider, out result);
        }

        public static {{data.TypeName}} Parse(ReadOnlySpan<char> s) => Parse(s, null);

        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "IFormatProvider is ignored for string length validation.")]
        public static {{data.TypeName}} Parse(ReadOnlySpan<char> s, IFormatProvider? provider)
        {
            if (TryParse(s, provider, out var result))
            {
                return result;
            }
            else
            {
                throw new FormatException(
                    $"The ID has invalid format. It must be a non-null string with maximum length of {MaxLength}."
                );
            }
        }

        public static bool TryParse(ReadOnlySpan<char> s, out {{data.TypeName}} result)
            => TryParse(s, null, out result);

        [SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "IFormatProvider is ignored for string length validation.")]
        public static bool TryParse(ReadOnlySpan<char> s, IFormatProvider? provider, out {{data.TypeName}} result)
        {
            if (s.Length <= MaxLength)
            {
                result = new {{data.TypeName}}(s.ToString());
                return true;
            }
            else
            {
                result = default;
                return false;
            }
        }

        public bool Equals({{data.TypeName}} other) => Value.Equals(other.Value, StringComparison.Ordinal);
        public int CompareTo({{data.TypeName}} other) => string.Compare(Value, other.Value, StringComparison.Ordinal);
        public override int GetHashCode() => Value.GetHashCode(StringComparison.Ordinal);
        public static implicit operator string({{data.TypeName}} id) => id.Value;

        public static bool operator <({{data.TypeName}} a, {{data.TypeName}} b) => a.CompareTo(b) < 0;
        public static bool operator <=({{data.TypeName}} a, {{data.TypeName}} b) => a.CompareTo(b) <= 0;
        public static bool operator >({{data.TypeName}} a, {{data.TypeName}} b) => a.CompareTo(b) > 0;
        public static bool operator >=({{data.TypeName}} a, {{data.TypeName}} b) => a.CompareTo(b) >= 0;

        static Expression<Func<string, {{data.TypeName}}>> IRawStringTypedId<{{data.TypeName}}>.FromDatabase { get; } = d => Parse(d);
        static Expression<Func<{{data.TypeName}}, {{data.TypeName}}, bool>> IRawStringTypedId<{{data.TypeName}}>.DatabaseEquals { get; } = (a, b) => a == b;

        public override string ToString() => Value;
        public string ToString(string? format, IFormatProvider? formatProvider) => Value;
        public bool TryFormat(Span<char> destination, out int charsWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
        {
            if (destination.Length >= Value.Length)
            {
                Value.CopyTo(destination);
                charsWritten = Value.Length;
                return true;
            }
            else
            {
                charsWritten = 0;
                return false;
            }
        }

        public bool TryFormat(Span<byte> utf8Destination, out int bytesWritten, ReadOnlySpan<char> format, IFormatProvider? provider)
            => Encoding.UTF8.TryGetBytes(Value, utf8Destination, out bytesWritten);
    }
}
""";
    }
}
