<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <OutputType>Library</OutputType>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <!-- This is a helper library, not a test project, so use extensibility core instead of test runner -->
    <PackageReference Remove="xunit.v3.mtp-v2" />
    <PackageReference Remove="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3.assert" />
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>
</Project>
