<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Polly" VersionOverride="8.6.6" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="LeanCode.Kratos.Client" />

    <ProjectReference Include="../LeanCode.Serialization/LeanCode.Serialization.csproj" />
  </ItemGroup>
</Project>
