<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Polly" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />

    <PackageReference Include="LeanCode.Kratos.Client" />

    <ProjectReference Include="../LeanCode.Serialization/LeanCode.Serialization.csproj" />
  </ItemGroup>

</Project>
