<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../../src/Infrastructure/LeanCode.SmsSender/LeanCode.SmsSender.csproj" />
    <ProjectReference Include="../../LeanCode.Test.Helpers/LeanCode.Test.Helpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog.Extensions.Logging" />
  </ItemGroup>
</Project>
