<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" VersionOverride="10.0.1" />
    <ProjectReference Include="../LeanCode.Logging/LeanCode.Logging.csproj" />

    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Formatting.Compact" />
    <PackageReference Include="Serilog.Settings.Configuration" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.Seq" />
  </ItemGroup>
</Project>
