<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../../src/Infrastructure/LeanCode.AzureIdentity/LeanCode.AzureIdentity.csproj" />
    <ProjectReference Include="../../LeanCode.Test.Helpers/LeanCode.Test.Helpers.csproj" />
  </ItemGroup>
</Project>
