FROM leancode.azurecr.io/dotnet:3.1

COPY test/Testing/LeanCode.IntegrationTestHelpers.Tests/docker/Docker.Directory.Build.props /app/Directory.Build.props

# Wait for SQL Server first
WORKDIR /app/code/test/Testing/LeanCode.IntegrationTestHelpers.Tests
ENV ASPNETCORE_TEST_CONTENTROOT_LEANCODE_INTEGRATIONTESTHELPERS_TESTS=/app/code/test/Testing/LeanCode.IntegrationTestHelpers.Tests
ENTRYPOINT sleep 10 && dotnet restore && dotnet watch test
