<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../../src/Infrastructure/LeanCode.Npgsql.ActiveDirectory/LeanCode.Npgsql.ActiveDirectory.csproj" />
    <ProjectReference Include="../../../src/Infrastructure/LeanCode.AuditLogs/LeanCode.AuditLogs.csproj" />

    <ProjectReference Include="../../LeanCode.Test.Helpers/LeanCode.Test.Helpers.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
  <PackageReference Include="Microsoft.Extensions.Configuration" VersionOverride="10.0.1" />
  </ItemGroup>
</Project>
